config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin, path: Spree.admin_path do
    resources :levels
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/level.rb
class Spree::Level < ApplicationRecord
  has_many :user,class_name: "Spree::User"
  has_one :upper_level,class_name: "Spree::Level", foreign_key: "upper_level_id"
  has_one :lower_level,class_name: "Spree::Level", foreign_key: "lower_level_id"
end

app/models/spree/user_decorator.rb
require 'ancestry'
Spree::User.class_eval do
  belongs_to :level,class_name: "Spree::Level", foreign_key: :spree_level_id
  has_ancestry
end

app/models/super.rb
# module Spree
#   def self.table_name_prefix
#     'spree_'
#   end
# end

app/controllers/spree/admin/levels_controller.rb
module Spree
  module Admin
class LevelsController < ResourceController
  before_action :set_spree_level, only: [:show, :edit, :update, :destroy]

  # GET /spree/levels
  def index
    @spree_levels = Spree::Level.all
  end

  # GET /spree/levels/1
  def show
  end

  # GET /spree/levels/new
  def new
    @spree_level = Spree::Level.new
  end

  # GET /spree/levels/1/edit
  def edit
  end

  # POST /spree/levels
  def create
    @spree_level = Spree::Level.new(spree_level_params)

    if @spree_level.save
      redirect_to @spree_level, notice: 'Level was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /spree/levels/1
  def update
    if @spree_level.update(spree_level_params)
      redirect_to @spree_level, notice: 'Level was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /spree/levels/1
  def destroy
    @spree_level.destroy
    redirect_to spree_levels_url, notice: 'Level was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spree_level
      @spree_level = Spree::Level.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def spree_level_params
      params.require(:spree_level).permit(:name)
    end
end
  end
end

app/helpers/spree/levels_helper.rb
module Spree::LevelsHelper
end

app/views/spree/admin/levels/_form.html.erb
<%= form_with(model: spree_level, local: true) do |form| %>
  <% if spree_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spree_level.errors.count, "error") %> prohibited this spree_level from being saved:</h2>

      <ul>
      <% spree_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :spree_level_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spree/admin/levels/edit.html.erb
<h1>Editing Spree Level</h1>

<%= render 'form', spree_level: @spree_level %>

<%= link_to 'Show', @spree_level %> |

app/views/spree/admin/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spree Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spree_levels.each do |spree_level| %>
      <tr>
        <td><%= spree_level.name %></td>
        <td><%= link_to 'Show', admin_level_path(spree_level) %></td>
        <td><%= link_to 'Edit', edit_admin_level_path(spree_level) %></td>
        <td><%= link_to 'Destroy', admin_level_path(spree_level), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/spree/admin/levels/new.html.erb
<h1>New Spree Level</h1>

<%= render 'form', spree_level: @spree_level %>

app/views/spree/admin/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spree_level.name %>
</p>

app/views/spree/admin/shared/_levels_sidebar_menu.html.erb
<% if can? :admin, Spree::Level%>
  <ul class="nav nav-sidebar">
    <%= tab Spree::Level, url: spree.admin_levels_url, icon: 'leaf', label: plural_resource_name(Spree::Level) %>
  </ul>
<% end %>